#%RAML 1.0 Library


traits:
  vread: 
    queryParameters:
      _format:
        required: false
        enum: [application/json, application/xml]
    responses:
      200:
        headers:
          ETag:
          Last-Modified: instant
        body:
          application/json:
            type: <<resourceName>>
  read:
    queryParameters:
      _format:
        required: false
        enum: [application/json, application/xml]
      _summary:
        required: false
        enum: ['true', 'false', text, data]
    headers:
      If-Modified-Since: 
        type: instant
        required: false
      If-None-Match:
        required: false
    responses:
      304:
        description: Not Modified
  update:
    responses:
      200:
        description: Updated
      201:
        description: Created
        headers:
          Location:
            example: http://xxx/condidition/123/_history/1
          Last-Modified: datetime
          ETag:
            example: '1.0'
      422:
        description: |
          Unprocessable Entity - the proposed resource violated applicable FHIR profiles or server business rules
  delete:
    responses:
      204:
        description: Deleted
  create:
    responses:
      201:
        description: Created
        headers:
          Location:
            example: http://xxx/Condidition/123/_history/1
          Last-Modified: datetime
          ETag:
            example: '1.0'
  search:
    queryParameters:
      _content:
        required: false
      _id:
        required: false 
      _lastUpdated:
        required: false
      _profile:
        required: false
      _query:
        required: false
      _security:
        required: false
      _tag:
        required: false
      _text:
        required: false
    responses:
      200:
        body:
          application/json:
            type: Bundle
  conformance:
    responses:
      200:
        body:
          application/json:
            type: Conformance
          application/xml:
            type: Conformance

  history:
    responses:
      200:
        body:
          application/json:
            type: Bundle

resourceTypes:
  fhirResourceType:
    post:
      is: [create]
      headers:
        If-None-Exist:
          required: false 
          description: name=value selective criteria
      body:
        application/json:
          type: <<resourcePathName>>
      responses:
        200:
          description: No match, resource created.
        412: 
          description: Precondition Failed error indicating the client's criteria were not selective enough.
    get:
      is: [search]
    put:
      description: Conditional update. Query params for selective name=value pair criteria
      is: [update]
      queryParameters:
      responses:
        412: 
          description: |
            Precondition Failed error indicating the client's criteria were not selective enough
    delete:
      is: [delete]
      queryParameters:
      responses:
        404: 
          description: Not found
        412:     
          description: Precondition Failed error indicating the client's criteria were not selective enough.
  fhirResource:
    get:
      is: [read]
      responses:
        200:
          body:
            application/json:
              type: <<resourcePathName>>  
    put:
      is: [update]
      body:
        application/json:
          type: <<resourcePathName>>
    delete:
      is: [delete]    
  fhirCompartment:
    get:
      is: [search]
  fhirSearch:
    post:
      body:
        application/x-www-form-urlencoded:   
          properties:
            _content:
              required: false
            _id:
              required: false
            _lastUpdated:
              required: false
            _profile:
              required: false
            _query:
              required: false
            _security:
              required: false
            _tag:
              required: false
            _text:
              required: false
      responses:
        200:
          body:
            application/json:
              type: Bundle
    get:
      is: [search]
  fhirVersionedResource:
    get:
      is: [vread: { resourceName: <<resourceName>> }]
  fhirHistory:
    get:
      is: [history]